spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/manas_db
    username: postgres
    password: nurs
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 20
    show-sql: false

  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
    encoding: UTF-8
    cache-duration: 3600

  thymeleaf:
    cache: false
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

  cache:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=6h
    cache-names:
      - timetable
      - food-today
      - food-weekly
      - translations
      - translation-entry

app:
  mail:
    from: ${MAIL_USERNAME:noreply@manas.edu}
    from-name: ManasMezun System
  jwt:
    secret: ${JWT_SECRET:change-me-in-prod-must-be-32-chars-min}
    expiration-ms: 86400000
  upload:
    dir: ./uploads
    avatar-path: /uploads/avatars/
    post-path: /uploads/posts/
  cloudinary:
    cloud-name: dpkxkjwmy
    api-key: 952176747147999
    api-secret: CcGE7JYPNbPxTMkxi5gSK3vri9E
  gemini:
    api-key: AIzaSyACV9S3vsdIhZWl4CaZUReMWE-QWi3FpTg
  groq:
    api-key: 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
  base-url: ${APP_BASE_URL:http://localhost:8081}
  recaptcha:
    site-key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
    secret-key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    verify-url: https://www.google.com/recaptcha/api/siteverify

server:
  port: ${PORT:8081}
  servlet:
    context-path: /
  compression:
    enabled: false
  tomcat:
    max-swallow-size: -1

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /v3/api-docs
  packages-to-scan: com.com.manasuniversityecosystem.api.v1.controller
  writer-with-default-pretty-printer: true
  cache:
    disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework.web.servlet.resource: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.com.manasuniversityecosystem: DEBUG